config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :martian_places
  resources :martian_weather_stations
  resources :urban_images
  # resources :city_images
  # resources :background_photos
  resources :cities do
    resources :background_photos, shallow: true
    resources :urban_images, shallow: true
  end
  get 'mars/index'
  resources :projects do
    resources :project_users, path: :users, module: :projects
  end
  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services

    root to: "users#index"
  end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  resources :notifications, only: [:index]
  resources :mars, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/martian_place.rb
class MartianPlace < ApplicationRecord
    has_many :martian_readings
    has_many :martian_weather_stations, through: :martian_readings

    after_commit        :schedule_update_readings_from_mars_weather_station_job, on: [:create, :update]
    
    def schedule_update_readings_from_mars_weather_station_job
        UpdateReadingsFromMarsWeatherStationJob.perform_later(id)
    end

end

app/controllers/martian_places_controller.rb
class MartianPlacesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :create]
  before_action :set_martian_place, only: [:show, :edit, :update, :destroy]

  # GET /martian_places
  # GET /martian_places.json
  def index
    @martian_places = MartianPlace.all
  end

  # GET /martian_places/1
  # GET /martian_places/1.json
  def show
    # @latest_seven_readings      = @martian_place.martian_readings.order(:sol).last(7)
    @latest_seven_readings = @martian_place.martian_readings.order(:sol)
                            .select(:sol, 
                                    :temp, 
                                    :temp_min, 
                                    :temp_max, 
                                    :wind_speed_av, 
                                    :wind_degrees, 
                                    :wind_compass_point, 
                                    :season, 
                                    :recorded_on
                            )
                            .last(7)
    @latest_reading             = @latest_seven_readings.last
  end

  # GET /martian_places/new
  def new
    @martian_place = MartianPlace.new
  end

  # GET /martian_places/1/edit
  def edit
  end

  # POST /martian_places
  # POST /martian_places.json
  def create
    @martian_place = MartianPlace.new(martian_place_params)

    respond_to do |format|
      if @martian_place.save
        format.html { redirect_to @martian_place, notice: 'Martian place was successfully created.' }
        format.json { render :show, status: :created, location: @martian_place }
      else
        format.html { render :new }
        format.json { render json: @martian_place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /martian_places/1
  # PATCH/PUT /martian_places/1.json
  def update
    respond_to do |format|
      if @martian_place.update(martian_place_params)
        format.html { redirect_to @martian_place, notice: 'Martian place was successfully updated.' }
        format.json { render :show, status: :ok, location: @martian_place }
      else
        format.html { render :edit }
        format.json { render json: @martian_place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /martian_places/1
  # DELETE /martian_places/1.json
  def destroy
    @martian_place.destroy
    respond_to do |format|
      format.html { redirect_to martian_places_url, notice: 'Martian place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_martian_place
      @martian_place = MartianPlace.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def martian_place_params
      params.require(:martian_place).permit(:name, :address, :latitude, :longitude)
    end
end

app/helpers/martian_places_helper.rb
module MartianPlacesHelper
end

app/views/martian_places/_data_previous_day.html.erb
      <div class="previous-day" >
        <h3 class="previous-day__sol">
          Sol
          <span data-sol>
            <%= data_previous_day.sol %>
          </span>
        </h3>
        <p class="previous-day__date" data-date><%= "#{time_ago_in_words(data_previous_day.recorded_on)} ago"  %></p>
        <p class="previous-day__temp high">
          High:
          <span data-temp-high="<%= data_previous_day.temp_max %>" >
                <%= data_previous_day.temp_max.round %>
          </span>
          °<span data-temp-unit></span>
        </p>
        <p class="previous-day__temp low">
          Low:
          <span data-temp-low="<%= data_previous_day.temp_min %>" >
            <%= data_previous_day.temp_min.round %>
          </span>
          °<span data-temp-unit></span>
        </p>
        <button id="<%= "#{data_previous_day.recorded_on.to_formatted_s(:number)}" %>"
                name="more-info"
                onClick="displaySelectedSol(this.id)"
                data-reading='{
                  "sol"                   : "<%= data_previous_day.sol %>",
                  "recorded-on"           : "<%= "#{time_ago_in_words(data_previous_day.recorded_on)} ago" %>",
                  "temp-high"             : <%= data_previous_day.temp_max %>,
                  "temp-low"              : <%= data_previous_day.temp_min %>,
                  "wind-degrees"          : "<%= data_previous_day.wind_degrees.to_i %>",
                  "wind-speed"            : <%= data_previous_day.wind_speed_av.to_i %>,
                  "wind-direction-text"   : "<%= data_previous_day.wind_compass_point || "--" %>"      
                }'
          class="previous-day__more-info" 
          data-select-button
        >
        <span class="previous-day__more-info__text">more info</span>
        <span class="previous-day__more-info__text-dot">&nbsp;</span>
        </button>
      </div>

app/views/martian_places/_form.html.erb
<%= form_with(model: martian_place, local: true) do |form| %>
  <% if martian_place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(martian_place.errors.count, "error") %> prohibited this martian_place from being saved:</h2>

      <ul>
      <% martian_place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, class: 'form-control' %>
  </div>

  <%= link_to 'Add Weather Station', new_martian_weather_station_path, target: :blank %>
  <div class="form-group">
    <%= form.label :martian_weather_station %>
    <%= form.collection_select(:martian_weather_station_id, 
      MartianWeatherStation.all, 
      :id, 
      :name,
      prompt: 'Select Weather Station') %>
  </div>

  <div class="form-group">
    <% if martian_place.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', martian_place, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if martian_place.persisted? %>
      <%= link_to "Cancel", martian_place, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", martian_places_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/martian_places/edit.html.erb
<h1>Edit Martian_place</h1>

<%= render 'form', martian_place: @martian_place %>

app/views/martian_places/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Martian_places</h1>
  </div>

  <div class="col-sm-6 text-right">
    <% if user_signed_in? %>
      <%= link_to new_martian_place_path, class: 'btn btn-primary' do %>
        Add New Martian place
      <% end %>  
    <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
    
        <th>Name</th>
    

            <th>Address</th>
            <th>Latitude</th>
            <th>Longitude</th>
            
      </tr>
    </thead>

    <tbody>
      <% @martian_places.each do |martian_place| %>
        <%= content_tag :tr, id: dom_id(martian_place), class: dom_class(martian_place) do %>
          
            <td><%= link_to martian_place.name, martian_place %></td>
          

                      <td><%= martian_place.address %></td>
                      <td><%= martian_place.latitude %></td>
                      <td><%= martian_place.longitude %></td>
          
          
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/martian_places/new.html.erb
<h1>New martian_place</h1>

<%= render 'form', martian_place: @martian_place %>

app/views/martian_places/show.html.erb
<% content_for :title, @martian_place.name %>

   <main class="mars-current-weather">
     <h1 class="main-title">
        Latest at <%= @martian_place.name %>  
        <% if user_signed_in? %>
          <% if current_user.admin %>
            <div>
              <%= link_to martian_places_path, class: 'btn btn-primary' do %>
                All Martian Places
              <% end %>            
            </div>
            <span>
              <%= link_to edit_martian_place_path(@martian_place), class: 'btn btn-primary' do %>
                Edit
              <% end %>            
            </span>
          <% end %>
        <% end %>

        <% unless @latest_reading %>
          <br>
          (no data available)
        <% end %>
     </h1>

      <div class="page-header">

      </div>

     <div class="date">
       <h2 class="section-title section-title--date">
          Sol 
          <span data-current-sol>
            <% if @latest_reading %>
              <%= @latest_reading.sol %>         
            <% end %>         
         </span>
        </h2>
       <p class="date__day" data-current-date>
          <% if @latest_reading %>
            <%= "#{time_ago_in_words(@latest_reading.recorded_on)} ago"  %>
          <% end %>
        </p>
     </div>

     <div class="temp">
       <h2 class="section-title">Temperature</h2>
       <p class="reading">
         High:
         <span data-current-temp-high>
            <% if @latest_reading %>
              <%= @latest_reading.temp_max.round %>
            <% end %>
          </span>
         
         °<span data-temp-unit></span>
        </p>
       <p class="reading">
         Low:
         <span data-current-temp-low>
            <% if @latest_reading %>
              <%= @latest_reading.temp_min.round %>
            <% end %>
          </span>
         °<span data-temp-unit></span>
        </p>
     </div>

     <div class="wind">
       <h2 class="section-title">Wind&#42;</h2>
       <p class="reading">
         <span data-wind-speed>
            <% if @latest_reading %>
              <%= @latest_reading.wind_speed_av || "--" %>          
            <% end %>
          </span>
         <span data-speed-unit></span>
        </p>

       <div class="wind__direction">
         <p class="sr-only" data-wind-direction-text>
          <% if @latest_reading %>
            <%= @latest_reading.wind_compass_point %>
          <% end %>
        </p>

         <!-- update --direction custom prop
              to change arrow direction -->
         <div class="wind__arrow" data-wind-direction-arrow></div>
       </div>
     </div> 

     <div class="info">
      <p>
        &#42; Due North &amp; 0 speed readings indicates no wind reading for that day.
      </p>
      <p>Collecting weather on the surface of Mars at <%= @martian_place.name %> 
          is only part of <%= @martian_place.martian_weather_stations.first.name %>'s mission. 
          <a href="https://mars.nasa.gov/insight/mission/overview/" target="_blank">Click here</a> 
          <a href="https://www.jpl.nasa.gov/missions/mars-science-laboratory-curiosity-rover-msl/">or here</a>
          to find out more.
      </p>
     </div>

     <div class="unit">
       <label for="cel">°C</label>
       <input type="radio" id="cel" name="unit" checked>
       <!-- when unit__toggle is clicked
            checkbox needs to change -->
       <button class="unit__toggle" data-unit-toggle></button>
       <label for="fah">°F</label>
       <input type="radio" id="fah" name="unit">
     </div> 

   </main>

   <div class="previous-weather" data-readings="<%= @latest_seven_readings.to_json %>">
     <!-- When clicked, toggle '.show-weather'
     to .previous-weather div -->
     <div class="previous-weather-button">
      <button for="weather-toggle" class="show-previous-weather"><span>&#8593;</span> <span class="sr-only">Show previous weather</span></button>
     </div>
     
     <h2 class="main-title previous-weather__title">Previous 7 days</h2> 

     <div class="previous-days" data-previous-sols >
        <% if @latest_seven_readings.length >  2 %>
            <%= render(partial: "data_previous_day", collection: @latest_seven_readings) %>
        <% else %>
            <%= render "data_previous_day_blank" %>
        <% end %>
     </div>
   </div>




    
<% wind_degrees =  @latest_reading.wind_degrees %>
<script>
  const API_KEY = 'DEMO_KEY'
  const API_URL = `https://api.nasa.gov/insight_weather/?api_key=${API_KEY}&feedtype=json&ver=1.0`

  const previousWeatherToggle   = document.querySelector('.show-previous-weather');
  const previousWeather         = document.querySelector('.previous-weather');
  const windDirectionArrow      = document.querySelector('[data-wind-direction-arrow]');
  const currentSolElement       = document.querySelector('[data-current-sol]');
  const currentDateElement      = document.querySelector('[data-current-date]');
  const currentTempHighElement  = document.querySelector('[data-current-temp-high]');
  const currentTempLowElement   = document.querySelector('[data-current-temp-low]');

const windSpeedElement          = document.querySelector('[data-wind-speed]');
const windDirectionText         = document.querySelector('[data-wind-direction-text]');

const unitToggle                = document.querySelector('[data-unit-toggle]')
const metricRadio               = document.getElementById('cel')
const imperialRadio             = document.getElementById('fah')

const previousSols              = document.querySelectorAll("button.previous-day__more-info");
const latestSolId               = previousSols[previousSols.length-1].id
  // const sols = getWeather()

  let selectedSolId
  selectedSolId = latestSolId

  updateUnits()
  displaySelectedSol(selectedSolId)
  displayPreviousTemperatures()

  // displaySelectedSol(latestSolIndex)
  // getWeather()
  //   .then(sols => {
  //     console.log(sols);
  // })

  // event listeners
  previousWeatherToggle.addEventListener('click', () => {
    previousWeather.classList.toggle('show-weather')
  })

  unitToggle.addEventListener('click', () => {
		let metricUnits = !isMetric()
		metricRadio.checked = metricUnits
		imperialRadio.checked = !metricUnits
		updateUnits()
		displaySelectedSol(selectedSolId)
    displayPreviousTemperatures()
		// displayPreviousSols(sols)
	})

	metricRadio.addEventListener('change', () => {
		updateUnits()
		displaySelectedSol(selectedSolId)
    displayPreviousTemperatures()
		// displayPreviousSols(sols)
	})

	imperialRadio.addEventListener('change', () => {
		updateUnits()
		displaySelectedSol(selectedSolId)
    displayPreviousTemperatures()
		// displayPreviousSols(sols)
	})

  windDirectionArrow.style.setProperty('--direction', `<%= @latest_reading.wind_degrees %>deg`)

  function displayPreviousTemperatures() {
    highTemps = document.querySelectorAll("span[data-temp-high]")
    lowTemps  = document.querySelectorAll("span[data-temp-low]")

    for (i = 0; i < highTemps.length; ++i) {
      highTemps[i].innerText = displayTemperature(highTemps[i]['dataset']['tempHigh']);
    } 
    for (i = 0; i < lowTemps.length; ++i) {
      lowTemps[i].innerText = displayTemperature(lowTemps[i]['dataset']['tempLow']);
    } 
  }

  function displaySelectedSol(sol_id) {
    el = document.getElementById(sol_id)
    let json = el.dataset.reading;
    let data = JSON.parse(json);
        // alert(data['sol'])
    selectedSolId = sol_id
    currentSolElement.innerText = data['sol']
    currentDateElement.innerText = data['recorded-on']
    currentTempHighElement.innerText =  displayTemperature(data['temp-high'])
    currentTempLowElement.innerText = displayTemperature(data['temp-low'] )
    windSpeedElement.innerText =  displaySpeed(data['wind-speed'])
    windDirectionArrow.style.setProperty('--direction', `${data['wind-degrees']}deg`)
    windDirectionText.innerText = data['wind-direction-text']
  }

  function displayTemperature(temperature) {

    let returnTemp = temperature
    if (!isMetric()) {
      returnTemp = (temperature *(9/5)) + 32
    }
    return Math.round(returnTemp)
  }

  function getWeather() {
    const el = document.querySelector('.previous-weather');

    let json = el.dataset.readings;
    let solData = JSON.parse(json);
    // return solData
    return Object.entries(solData).map(([sol, data]) => {
      return {
        sol: sol,
        maxTemp: data.temp_max,
        minTemp: data.temp_min,
        windSpeed: data.wind_speed_av,
        windDirectionDegrees: data.wind_degrees,
        windDirectionCardinal: data.wind_compass_point,
        date: new Date(data.recorded_on)
      }
    })
  }

  function displaySpeed(speed) {
    // alert("Speed Metric is " + isMetric())

    let returnSpeed = speed
    if (!isMetric()) {
      returnSpeed = speed / 1.609
    }
    
    return Math.round(returnSpeed)
  }

  function updateUnits() {
    const speedUnits = document.querySelectorAll('[data-speed-unit]')
    const tempUnits = document.querySelectorAll('[data-temp-unit]')
    speedUnits.forEach(unit => {
      unit.innerText = isMetric() ? 'kph' : 'mph'
    })
    tempUnits.forEach(unit => {
      unit.innerText = isMetric() ? 'C' : 'F'
    })
  }

  function isMetric() {
	  return metricRadio.checked
  }
</script>    

app/views/martian_places/show_old.html.erb
<div class="page-header">
  <%= link_to martian_places_path, class: 'btn btn-default' do %>
    All Martian_places
  <% end %>
  <%= link_to edit_martian_place_path(@martian_place), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show martian_place</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @martian_place.name %></dd>

  <dt>Address:</dt>
  <dd><%= @martian_place.address %></dd>

  <dt>Latitude:</dt>
  <dd><%= @martian_place.latitude %></dd>

  <dt>Longitude:</dt>
  <dd><%= @martian_place.longitude %></dd>

  <dt>Weather Stations:</dt>
  <dd>
    <ul>
      <% @martian_place.martian_weather_stations.select(:id, :name).group(:id).each do |station|%>
        <li><%= station.name %></li> 
      <% end %>    
    </ul>
  </dd>

</dl>