config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :martian_places
  resources :martian_weather_stations
  resources :urban_images
  # resources :city_images
  # resources :background_photos
  resources :cities do
    resources :background_photos, shallow: true
    resources :urban_images, shallow: true
  end
  get 'mars/index'
  resources :projects do
    resources :project_users, path: :users, module: :projects
  end
  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services

    root to: "users#index"
  end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  resources :notifications, only: [:index]
  resources :mars, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/martian_weather_station.rb
class MartianWeatherStation < ApplicationRecord
    has_many :martian_readings
    has_many :martian_places, through: :martian_readings
    # has_many :martian_places, through: :martian_readings
end

app/controllers/martian_weather_stations_controller.rb
class MartianWeatherStationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_martian_weather_station, only: [:show, :edit, :update, :destroy]

  # GET /martian_weather_stations
  # GET /martian_weather_stations.json
  def index
    @martian_weather_stations = MartianWeatherStation.all
  end

  # GET /martian_weather_stations/1
  # GET /martian_weather_stations/1.json
  def show
  end

  # GET /martian_weather_stations/new
  def new
    @martian_weather_station = MartianWeatherStation.new
  end

  # GET /martian_weather_stations/1/edit
  def edit
  end

  # POST /martian_weather_stations
  # POST /martian_weather_stations.json
  def create
    @martian_weather_station = MartianWeatherStation.new(martian_weather_station_params)

    respond_to do |format|
      if @martian_weather_station.save
        format.html { redirect_to @martian_weather_station, notice: 'Martian weather station was successfully created.' }
        format.json { render :show, status: :created, location: @martian_weather_station }
      else
        format.html { render :new }
        format.json { render json: @martian_weather_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /martian_weather_stations/1
  # PATCH/PUT /martian_weather_stations/1.json
  def update
    respond_to do |format|
      if @martian_weather_station.update(martian_weather_station_params)
        format.html { redirect_to @martian_weather_station, notice: 'Martian weather station was successfully updated.' }
        format.json { render :show, status: :ok, location: @martian_weather_station }
      else
        format.html { render :edit }
        format.json { render json: @martian_weather_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /martian_weather_stations/1
  # DELETE /martian_weather_stations/1.json
  def destroy
    @martian_weather_station.destroy
    respond_to do |format|
      format.html { redirect_to martian_weather_stations_url, notice: 'Martian weather station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_martian_weather_station
      @martian_weather_station = MartianWeatherStation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def martian_weather_station_params
      params.require(:martian_weather_station).permit(:name, :latitude, :latitude, :longitude, :longitude, :data_connection)
    end
end

app/helpers/martian_weather_stations_helper.rb
module MartianWeatherStationsHelper
end

app/views/martian_weather_stations/_form.html.erb
<%= form_with(model: martian_weather_station, local: true) do |form| %>
  <% if martian_weather_station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(martian_weather_station.errors.count, "error") %> prohibited this martian_weather_station from being saved:</h2>

      <ul>
      <% martian_weather_station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :data_connection %>
    <%= form.text_field :data_connection, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if martian_weather_station.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', martian_weather_station, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if martian_weather_station.persisted? %>
      <%= link_to "Cancel", martian_weather_station, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", martian_weather_stations_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/martian_weather_stations/edit.html.erb
<h1>Edit Martian_weather_station</h1>

<%= render 'form', martian_weather_station: @martian_weather_station %>

app/views/martian_weather_stations/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Martian_weather_stations</h1>
  </div>

  <div class="col-sm-6 text-right">
  <%= link_to new_martian_weather_station_path, class: 'btn btn-primary' do %>
    Add New Martian weather station
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
    
        <th>Name</th>
    

            <th>Latitude</th>
            <th>Latitude</th>
            <th>Longitude</th>
            <th>Longitude</th>
            
      </tr>
    </thead>

    <tbody>
      <% @martian_weather_stations.each do |martian_weather_station| %>
        <%= content_tag :tr, id: dom_id(martian_weather_station), class: dom_class(martian_weather_station) do %>
          
            <td><%= link_to martian_weather_station.name, martian_weather_station %></td>
          

                      <td><%= martian_weather_station.latitude %></td>
                      <td><%= martian_weather_station.latitude %></td>
                      <td><%= martian_weather_station.longitude %></td>
                      <td><%= martian_weather_station.longitude %></td>
          
          
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/martian_weather_stations/new.html.erb
<h1>New martian_weather_station</h1>

<%= render 'form', martian_weather_station: @martian_weather_station %>

app/views/martian_weather_stations/show.html.erb
<div class="page-header">
  <%= link_to martian_weather_stations_path, class: 'btn btn-default' do %>
    All Martian_weather_stations
  <% end %>
  <%= link_to edit_martian_weather_station_path(@martian_weather_station), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show martian_weather_station</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @martian_weather_station.name %></dd>

  <dt>Latitude:</dt>
  <dd><%= @martian_weather_station.latitude %></dd>

  <dt>Longitude:</dt>
  <dd><%= @martian_weather_station.longitude %></dd>

  <dt>Data Connection:</dt>
  <dd><%= @martian_weather_station.data_connection %></dd>

</dl>